{% set name = "spatial-image" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spatial_image-{{ version }}.tar.gz
  sha256: e7fb185644093e96cac510c4184f2777b965b5a7ca25688f379e9acb48e3e07d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}
    - xarray
    - xarray-dataclasses >=1.9.1

test:
  imports:
    - spatial_image
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/spatial-image/
  summary: A multi-dimensional spatial image data structure for scientific Python.
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/spatial-image/spatial-image

extra:
  recipe-maintainers:
    - thewtex
    - goanpeca
    - giovp
    - LucaMarconato
