{% set name = "spatial-image" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spatial_image-{{ version }}.tar.gz
  sha256: 55373e54a5e4c8de8e2cf3039f2caa4efb23fad1ac1137f279172fb31f979e2e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core
    - pip
    - python >=3.8
  run:
    - numpy
    - python >=3.8
    - xarray
    - xarray-dataclasses >=1.1.0

test:
  imports:
    - spatial_image
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/spatial-image/
  summary: A multi-dimensional spatial image data structure for scientific Python.
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/spatial-image/spatial-image

extra:
  recipe-maintainers:
    - goanpeca
