{% set name = "spatial-image" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spatial_image-{{ version }}.tar.gz
  sha256: 84b5eae611674c7951e8019d10f7c0c2698d7e1e4bc1f4329fdc35fe3fdc0ccd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}
    - xarray
    - xarray-dataclasses >=1.1.0

test:
  imports:
    - spatial_image
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/spatial-image/
  summary: A multi-dimensional spatial image data structure for scientific Python.
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/spatial-image/spatial-image

extra:
  recipe-maintainers:
    - goanpeca
    - giovp
    - LucaMarconato
